### ISSUE TITLE
get_attendance raise error TCP packet invalid

### ISSUE THREAD

**Issue by cyansilver** [kurenai-ryu/pyzk#6]
**Describe the bug**
The method get_attendance() cannot get all the records. Then after that, call any functions even conn.disconnect()

**To Reproduce**
1. there are 4 records
2. call get_attendance()
3. get 2 records
4. call conn.disconnect()
5. get error

**Expected behavior**
Should get all attendance records and disconnect normally.

**Capture Data**
Error message:
`Traceback (most recent call last):
  File "sync.py", line 7, in <module>
    attendances = attendance_handler.pull_data('192.168.1.98', 4370, 5)
  File "/tracking/app/attendance/handler.py", line 46, in pull_data
    conn.disconnect()
  File "/tracking/zk/base.py", line 351, in disconnect
    cmd_response = self.__send_command(const.CMD_EXIT)
  File "/tracking/zk/base.py", line 225, in __send_command
    raise ZKNetworkError(str(e))
zk.exception.ZKNetworkError: TCP packet invalid`

**System (please complete the following information):**
 - OS: Ubuntu
 - Python version: 2.7

**Additional context**
I checked the get_attendance function and notice sth, not sure if it's related:
- the size here return 112 https://github.com/kurenai-ryu/pyzk/blob/master/zk/base.py#L1501
- the total size here return 160 https://github.com/kurenai-ryu/pyzk/blob/master/zk/base.py#L1505
- the record_size is 40 https://github.com/kurenai-ryu/pyzk/blob/master/zk/base.py#L1506
- So it go to this loop https://github.com/kurenai-ryu/pyzk/blob/master/zk/base.py#L1544
- But the size of attendance_data (112 - 4) = 108 so only two loops.

**Comment by kurenai-ryu** [comment]
**ok, I'll need a packet capture, and if you can, initiate the instance with `verbose=True` and send both the [pncap](https://youtu.be/AsDedCgkhnA) and the verbose output.** 

about the sizes, 160 should be all the attendances records, (record_size should be 40 it's ok) it's embedded on the data. but it seems it couldn't read all the data  (only received 112 bytes instead of 162 bytes (160 + size[2])) I fixed a minor bug with the latest commit, but maybe it wasn't completely fixed. if the device is sending the rest of the data and we don't acknowledge it, it hangs and you can't do anything more.

by the mean time, please test with `force_udp=True` (if it's a older device) which is a more consistent communication, also please make sure you are using the latest version: commit 0e1cfd3

and also, please tell me the model of your device (if possible with firmware version both form the display and from the get_firmware_version() response[which seems different who knows why] )

**Comment by kurenai-ryu** [comment]
No further response, assumed it works with latest commit
